# WebBasicsFrame Config File

# ProjectName: web-basics-framework-template
# ProjectDescription: Web Basics Framework Template
# ProjectAuthor: lZiMUl

# WebServer Config
[webServer]
host = "localhost"
port = "8080"

# WebSocket Config
[webSocket]
host = "localhost"
port = "8081"

# Exterior WebSocket Config
[exteriorWebSocket]
host = "localhost"
port = "8081"

# Connect mongoDB Config
[mongodb]
username = "publicTest"
password = "publicTest"
hostname = "userinfo.giisy.mongodb.net"
database = "myFirstDatabase"